apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mautic-unsubscribe-proxy-ingress
  namespace: simplify-web
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  labels:
    app.kubernetes.io/name: mautic-unsubscribe-proxy
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - unsubscribe.engage.wapsol.de
      secretName: mautic-unsubscribe-proxy-tls
  rules:
    - host: unsubscribe.engage.wapsol.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mautic-unsubscribe-proxy
                port:
                  number: 80
